### ISSUE TITLE
file absent in /opt/davinci_resolve/ path

### ISSUE THREAD

**Issue by AshutoshBrl** [leinardi/JDInstaller#12]
### Step 1: Are you in the right place?
- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests.
- [ ] I have verified that I am using the latest version of the playbook.

### Step 2: Describe your environment
- Ansible version: `core 2.17.6`
- Operating System: `ubuntu 24.04.1`
- Ansible playbook: `ubuntu-setuo`
- Role (if applicable): `?`

#### Steps to reproduce:
1. git checkout davinci
2. make install TAGS=davinci_resolve

#### Observed Results:

*

#### Expected Results:

* download and install the davinci resolve with necessary dependencies.

#### Relevant Code:

```yaml
- name: Example task
  hosts: localhost
  tasks:
    - name: Print Hello World
      debug:
        msg: "Hello, world!"
```

#### Error/Log Output:

```bash
TASK [davinci_resolve : Set permissions for the installer] *********************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "file (/opt/davinci-resolve/DaVinci_Resolve_19.1.0_Linux.run) is absent, cannot continue", "path": "/opt/davinci-resolve/DaVinci_Resolve_19.1.0_Linux.run", "state": "absent"}

PLAY RECAP *********************************************************************
localhost                  : ok=29   changed=4    unreachable=0    failed=1    skipped=5    rescued=0    ignored=0  
```
the file seems to be present in that path even after this error
```bash
ash@ash-Nitro-AN515-45:~/JDInstaller$ ls /opt/davinci-resolve/
DaVinci_Resolve_19.1_Linux.run  Linux_Installation_Instructions.pdf
```

**Comment by leinardi** [comment]
be careful: there was actually a bug, please check my previous comment: :https://github.com/leinardi/JDInstaller/issues/12#issuecomment-2482657721

**Comment by AshutoshBrl** [comment]
Thank you for the fix. pulled the changes and the playbook worked.
