### ISSUE TITLE
How to uninstall

### ISSUE THREAD

**Issue by Vidyut** [leinardi/JDInstaller#16]
I installed for the Davinci Resolve, but while the installation went well, I can't get Resolve to run. I suspect this may be about Nvidia and Ubuntu, which is another juggling trick. At the same time, there isn't much point keeping it if I can't use it.

But now I'm stuck with having installed ansible as well as Resolve and with no evident ways to remove either. I see in the other thread that there is no uninstall option offered, but shouldn't this be made clear upfront when offering installers that can install gigabytes worth software that is potentially unusable?

I have work on this machine. I can't exactly factory reset it.

Help. At this point any ideas just to remove Resolve will be appreciated. Is it fine if I just delete the install and the launch files?

**Comment by leinardi** [comment]
Please make sure to use the correct Nvidia drivers: https://www.youtube.com/watch?v=Z29Fpx8KClw

If that doesn't work, you can find instructions on how to remove Davinci Resolve here: https://github.com/leinardi/JDInstaller/blob/master/roles/davinci_resolve/DaVinciResolve.md

To remove Ansible, run this in a terminal: `sudo apt remove ansible`

**Comment by Vidyut** [comment]
Thanks. Much appreciated.
