### ISSUE TITLE
not open software

### ISSUE THREAD

**Issue by Abrillant-Lee** [leinardi/JDInstaller#18]
sudo /opt/davinci-resolve/bin/resolve 
ActCCMessage Already in Table: Code= c005, Mode= 13, Level=  1, CmdKey= -1, Option= 0
ActCCMessage Already in Table: Code= c006, Mode= 13, Level=  1, CmdKey= -1, Option= 0
ActCCMessage Already in Table: Code= c007, Mode= 13, Level=  1, CmdKey= -1, Option= 0
ActCCMessage Already in Table: Code= 2282, Mode=  0, Level=  0, CmdKey= 8, Option= 0
19.1.2.0003 Linux/Clang x86_64
Main thread starts: D3776000
0x7b89d3776000 | Undefined            | INFO  | 2024-12-27 00:14:11,088 | --------------------------------------------------------------------------------
0x7b89d3776000 | Undefined            | INFO  | 2024-12-27 00:14:11,088 | Loaded log config from /root/.local/share/DaVinciResolve/configs/log-conf.xml
0x7b89d3776000 | Undefined            | INFO  | 2024-12-27 00:14:11,088 | --------------------------------------------------------------------------------

**Comment by leinardi** [comment]
Please file a proper issue report:
```
### Step 1: Are you in the right place?
- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests.
- [ ] I have verified that I am using the latest version of the playbook.

### Step 2: Describe your environment
- Ansible version: `?`
- Operating System: `?`
- Ansible playbook: `?`
- Role (if applicable): `?`

### Step 3: Describe the problem:

#### Steps to reproduce:
1. _____
2. _____
3. _____

#### Observed Results:
<!-- What happened? This could be a description, error message, or log output. -->
*

#### Expected Results:
<!-- What did you expect to happen? -->
*

#### Relevant Code:
<!-- Please wrap code with correct syntax highlighting. -->
```yaml
- name: Example task
  hosts: localhost
  tasks:
    - name: Print Hello World
      debug:
        msg: "Hello, world!"
```

#### Error/Log Output:

```bash
TASK [example : Print Hello World] ********************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "An example error"}
```



```
